name: deploy-shiny

on:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install shiny
      - run: R -e 'install.packages(c("shiny", "rsconnect"), type = "binary")'
        
    # aktualizace času
      - run: Rscript timestamp.R
    
    # nasazeni do shinyapps.io
      - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='trusinas', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appFileManifest = 'fileManifest.txt', appName = 'ga_test')"
