name: deploy-shiny

on:
  schedule:
    - cron: '0/15 * * * *'
  workflow_dispatch:

jobs:
  deploy-shiny:
    runs-on: ubuntu-20.04
    steps:
    # zkopírování repozitory
      - uses: actions/checkout@v2
    
    # instalace R
      - name: setup-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.0.5'
    
    # instalace závislostí
      - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      
    # instalace knihoven a závislostí pomocí renv
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
        
    # aktualizace času
      - run: Rscript timestamp.R
    
    # nasazeni do shinyapps.io
      - run: Rscript -e "rsconnect::setAccountInfo(name='trusinas', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
      - run: Rscript -e "rsconnect::deployApp(appFileManifest = 'fileManifest.txt', appName = 'ga_test')"
